### ISSUE TITLE
Improperly vendored glog

### ISSUE THREAD

**Issue by tsuna** [snowflakedb/gosnowflake#190]
As of commit 56b1dfc3c5789891147ee73356ec5b4f0bd416e0 for some reason you guys decided to copy-paste glog into your repo instead of using vendoring.  Can you please not copy-paste the glog code in your project?  Not only it forces us downstream to vendor this "vendored" code, but also it removes our ability to override the glog implementation used.

It's not clear to me why you did this but if it's because you intend to change glog, then re-vendor it and add this to your `Gopkg.toml`:
```toml
[[override]]
  name = "github.com/golang/glog"
  # Don't use upstream glog, force our fork instead.
  source = "https://github.com/snowflakedb/glog.git"
  branch = "master"
```

And then make whatever changes you want to your fork of the upstream repo.
